version: '3'

volumes:
  postgres_data:
      driver: local

services:
  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: POSTGRES
        DB_ADDR: postgres
        DB_DATABASE: keycloak
        DB_USER: keycloak
        DB_SCHEMA: public
        DB_PASSWORD: 'LrohDLX-yourDBpassword'
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: yourKeycloakPassword
        PROXY_ADDRESS_FORWARDING: 'true'
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
        #config @ https://brianturchyn.net/traefik-forwardauth-support-with-keycloak/
      ports:
        - 8084:8080
      restart: unless-stopped
      networks:
        - proxy
        - postgres_postgres
      labels:
          - "traefik.enable=true"
          - "traefik.docker.network=proxy"
          - "traefik.http.routers.keycloak.rule=Host(`auth.guidongui.com`)"
          - "traefik.http.routers.keycloak.entrypoints=web, websecure"
          - "traefik.http.routers.keycloak.tls.certresolver=production"
          - "traefik.http.services.keycloak.loadbalancer.server.port=8080"
          - "traefik.protocol=https"

networks:
  proxy:
    external: true
  postgres_postgres:
    external: true