---
version: "2.1"
services:
  radarr:
    image: lscr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /home/guido/docker_projects/linuxserver_radarr/config:/config
      - /home/guido/data:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    networks:
      - proxy
      - media
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.radarr.rule=Host(`radarr.guidongui.com`)"
      - "traefik.http.routers.radarr.entrypoints=web, websecure"
      - "traefik.http.routers.radarr.tls.certresolver=production"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      - "traefik.protocol=https"
      - "traefik.http.routers.radarr.middlewares=traefik-forward-auth"

networks:
  media:
    external: true
  proxy:
    external: true