---
    version: "2.1"
    services:
      filebrowser:
        image: filebrowser/filebrowser
        container_name: filebrowser

        environment:
          - PUID=1000
          - PGID=1000

        volumes:
          - /home/guido/:/srv
          - /home/guido/docker_projects/filebrowser_filebrowser/database/filebrowser.db:/database/filebrowser.db
          - /home/guido/docker_projects/filebrowser_filebrowser/config/settings.json:/config/settings.json
        
        labels:
          # - "traefik.enable=true"
          # - "traefik.http.routers.filebrowser.rule=Host(`files.guidongui.com`)"
          # - "traefik.http.routers.filebrowser.entrypoints=web, websecure"
          # - "traefik.http.routers.filebrowser.tls.certresolver=production"
          # - "traefik.http.services.filebrowser.loadbalancer.server.port=80"
          # - "traefik.protocol=https"
          # - "traefik.http.routers.filebrowser.middlewares=traefik-forward-auth"

        ports:
          - 8082:80
          
        restart: unless-stopped

        networks:
          - proxy
          
    networks:
      proxy:
        external: true
