version: '3'

services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    ports:
      - "80:80"
      - "443:443"
      # (Optional) Expose Dashboard
    #  - "8083:8080"  # Don't do this in production!
    volumes:
#      - /home/guido/docker_projects/traefik/log:/traefik/log
      - /home/guido/docker_projects/traefik/config/traefik.yml:/traefik.yml:ro
      - /home/guido/docker_projects/traefik/log/access.log:/etc/traefik/log/access.log
      - /home/guido/docker_projects/traefik/log/traefik.log:/etc/traefik/log/traefik.log
      - /home/guido/docker_projects/traefik/config/:/etc/traefik/config/
      - /home/guido/docker_projects/traefik/certs/acme.json:/etc/traefik/certs/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks:
      - proxy
  forwardauth:
    image: "mesosphere/traefik-forward-auth"
    networks:
      - proxy
    environment:
      - SECRET=wWGV75NksMHmXPvI2Ht9AFVQe
      - PROVIDER_URI=https://auth.yourdns.it/auth/realms/yourrealm
      - CLIENT_ID=yourclientid
      - CLIENT_SECRET=yourclientpw
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.services.forwardauth.loadbalancer.server.port=4181"
      - "traefik.http.routers.forwardauth.entrypoints=web, websecure"
      - "traefik.http.routers.forwardauth.rule=Path(`/_oauth`)"
      - "traefik.http.routers.forwardauth.middlewares=traefik-forward-auth"
      - "traefik.protocol=http"
      # - "traefik.http.routers.traefik-forward-auth.tls.certresolver=production"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://forwardauth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.trustForwardHeader=true"
  whoami:
    image: "nginxdemos/hello"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`webtest.guidongui.it`)"
      - "traefik.http.routers.whoami.entrypoints=web, websecure"
      - "traefik.http.routers.whoami.tls.certresolver=staging"
    networks:
      - proxy
 

networks:
  proxy:
    external: true