---
version: "2.1"
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
    volumes:
      - /home/guido/docker_projects/linuxserver_sonarr/config:/config
      - /home/guido/data:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - proxy
      - media
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.guidongui.com`)"
      - "traefik.http.routers.sonarr.entrypoints=web, websecure"
      - "traefik.http.routers.sonarr.tls.certresolver=production"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
      - "traefik.protocol=https"
      - "traefik.http.routers.sonarr.middlewares=traefik-forward-auth"

networks:
  media:
    external: true
  proxy:
    external: true