---
version: "2.1"
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - WEBUI_PORT=8081
    volumes:
      - /home/guido/qbittorrent/config:/config
      # - /home/guido/plex:/downloads
      - /home/guido/data/torrents:/data/torrents
    ports:
      - 6881:6881
      - 6881:6881/udp
      - 8081:8081
    restart: unless-stopped
    networks:
      - proxy
      - media
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.torrent.rule=Host(`torrent.guidongui.com`)"
      - "traefik.http.routers.torrent.entrypoints=web, websecure"
      - "traefik.http.routers.torrent.tls.certresolver=production"
      - "traefik.http.services.torrent.loadbalancer.server.port=8081"
      - "traefik.protocol=https"
      - "traefik.http.routers.torrent.middlewares=traefik-forward-auth"

networks:
  media:
    external: true
  proxy:
    external: true
    
    
