version: '3.1'

# Created on prometheus definition
networks:
  prometheus_monitoring:
    driver: bridge
    external: true

services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - /data_path/grafana:/var/lib/grafana
      - /data_path/grafana-provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=username
      - GF_SECURITY_ADMIN_PASSWORD=password
      - GF_USERS_ALLOW_SIGN_UP=false
    restart: unless-stopped
    networks:
      - prometheus_monitoring