---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/usrname/docker_projects/linuxserver_jackett/config:/config
      - /home/usrname/data/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - media
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/Rome
    ports:
      - 8191:8191
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    external: true