---
version: "2.1"
services:
  jackett:
    image: lscr.io/linuxserver/jackett
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - AUTO_UPDATE=true #optional
      # - RUN_OPTS=<run options here> #optional
    volumes:
      - /home/guido/docker_projects/linuxserver_jackett/config:/config
      - /home/guido/data/torrents:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    external: true