---
    version: "2.1"
    services:
      homer:
        image: b4bz/homer:latest
        container_name: homer

        environment:
          - PUID=1000
          - PGID=1000

        volumes:
          - /home/guido/docker_projects/b4bz_homer/www/assets:/www/assets

        ports:
          - 8080:8080
          
        restart: unless-stopped
        
        networks:
          - proxy
          
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.homer.rule=Host(`landing.guidongui.com`)"
          - "traefik.http.routers.homer.entrypoints=web, websecure"
          - "traefik.http.routers.homer.tls.certresolver=production"
          - "traefik.http.services.homer.loadbalancer.server.port=8080"
          - "traefik.protocol=https"
          - "traefik.http.routers.homer.middlewares=traefik-forward-auth"
          
    networks:
      proxy:
        external: true
