---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - JELLYFIN_PublishedServerUrl=93.51.20.186 #optional
    volumes:
      - /home/usrname/docker_projects/linuxserver_jellyfin/config:/config
      - /home/usrname/data/media/tv:/data/tv
      - /home/usrname/data/media/movies:/data/movies
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped