global:
  checkNewVersion: true
  sendAnonymousUsage: false  # true by default

# (Optional) Log information
# ---
log:
  level: WARNING  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  format: common  # common, json, logfmtx
# filePath: /var/log/traefik/traefik.log
  filePath: /etc/traefik/log/traefik.log

# (Optional) Accesslog
# ---
accesslog:
  format: common  # common, json, logfmt
#filePath: /var/log/traefik/access.log
  filePath: /etc/traefik/traefik/access.log


# (Optional) Enable API and Dashboard
# ---
api:
  dashboard: false  # true by default
  #dashboard: true 
  insecure: false  
  #insecure: true  # Don't do this in production!

# Entry Points configuration
# ---
entryPoints:
  web:
    address: :80
    # (Optional) Redirect to HTTPS
    # ---
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https

  websecure:
    address: :443

# Configure your CertificateResolver here...
# ---
certificatesResolvers:
  staging:
    acme:
      email: asd@asdasd.it
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-staging-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web
  production:
    acme:
      email: asd@asdasd.it
      storage: /etc/traefik/certs/acme.json
      caServer: "https://acme-v02.api.letsencrypt.org/directory"
      httpChallenge:
        entryPoint: web

# (Optional) Overwrite Default Certificates
# tls:
#   stores:
#     default:
#       defaultCertificate:
#         certFile: /etc/traefik/certs/cert.pem
#         keyFile: /etc/traefik/certs/cert-key.pem

providers:
  docker:
    exposedByDefault: false  # Default is true
  file:
    # watch for dynamic configuration changes
    directory: /etc/traefik
    watch: true
