version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:java17
    volumes:
    - /docker_project/minecraft_server/modpacks:/modpacks:ro
    - /docker_project/minecraft_server/plugins:/plugins:ro
    # - /docker_project/minecraft_server/ops/ops_file.json:/ops_file.json:ro
    - /home/$user/data:/data
    environment:
      EULA: "true"
      TYPE: "FORGE"
      VERSION: "LATEST"
      MOTD: "Welcome to the §l§cMinecraft§r §nserver powered by §l§cGuidongui§r"
      # OPS_FILE: "/ops_file.json"
      OPS: Guidongui
      ENABLE_WHITELIST: "TRUE"
      ENFORCE_WHITELIST: "TRUE"
    restart: unless-stopped
    ports:
      - "25565:25565"