---
version: "2.1"
services:
  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Rome
      - BASE_URL=/ombi #optional
    volumes:
      - /home/usrname/docker_projects/linuxserver_jackett/config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    networks:
      - media

networks:
  media:
    external: true